### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by kamilghais** [google/edash-packager#3] opened 2014-12-09 16:28 UTC
Hi,
can someone please compile the windows binaries for us? We did not succeed creating ninja build file, it says the 'zlib/zlib.gyp' is missing.
Help appreciated.
  Kamil Ghais

**Comment by sanbhatt** [comment] 2015-02-16 18:44
Hi kqyang, is there a timeline to when windows build may be fixed?

**Comment by kqyang** [comment] 2015-02-18 17:57
No, we don't have a timeline for windows support at this time.

**Comment by kqyang** [comment] 2015-07-14 00:48
Duplicate of issue #22

**Closed by kqyang** 2015-07-14 00:48 UTC
