### ISSUE TITLE
Can't not sync on Mac

### ISSUE THREAD

**Issue by leeight** [google/edash-packager#14] opened 2015-04-01 01:37 UTC
```
gyp: Call to '/bin/echo -n ${HOME}/goma' returned exit status 0.
Error: Command /usr/bin/python src/gyp_packager.py --depth=src/packager returned non-zero exit status 1 in /Volumes/HDD/Users/leeight/local/case/inf/bec/edash_packager
```

**Comment by leeight** [comment] 2015-04-01 01:41
```
gyp: /Volumes/HDD/Users/leeight/local/case/inf/bec/edash_packager/src/packager/third_party/mach_override/mach_override.gyp not found (cwd: /Volumes/HDD/Users/leeight/local/case/inf/bec/edash_packager)
```

**Comment by kqyang** [comment] 2015-04-01 01:41
Duplicate of issue #10

**Closed by kqyang** 2015-04-01 01:41 UTC
