### ISSUE TITLE
Unable to run gclient sync

### ISSUE THREAD

**Issue by sarbjit-longia** [google/edash-packager#43] opened 2015-10-20 16:12 UTC
I followed instruction on the main page to get the code and third parties but it is giving me following error:
//////////////////////////////////////////////////////
c:\Sarbjit\SDKs\edash_packager>gclient sync
Syncing projects: 100% (19/19), done.
________ running 'C:\Sarbjit\SDKs\depot_tools\python276_bin\python.exe src/packager/tools/clang/scripts/update
.py --if-needed' in 'c:\Sarbjit\SDKs\edash_packager'
________ running 'C:\Sarbjit\SDKs\depot_tools\python276_bin\python.exe src/gyp_packager.py --depth=src/package
r' in 'c:\Sarbjit\SDKs\edash_packager'
Updating projects from gyp files...
gyp: c:\Sarbjit\SDKs\edash_packager\src\packager\third_party\zlib\zlib.gyp not found (cwd: c:\Sarbjit\SDKs\edash_packager)

Error: Command 'C:\\Sarbjit\\SDKs\\depot_tools\\python276_bin\\python.exe src/gyp_packager.py --depth=src/packager' returned non-zero exit status 1 in c:\Sarbjit\SDKs\edash_packager
//////////////////////////////////////////////////////////////

**Comment by kqyang** [comment] 2015-10-20 17:00
Hi Sarbjit, looks like you are running on Windows, which is not supported yet. You may want to try Docker: https://github.com/google/edash-packager#using-docker-for-testing--development

Duplicate of #22 

We'd like to have it supported on Windows directly, but we don't have resource right now...

**Closed by kqyang** 2015-10-20 17:00 UTC

**Comment by sarbjit-longia** [comment] 2015-10-20 18:08
When you say its not supprted is it edash-packager itself or the tools to build it

**Comment by kqyang** [comment] 2015-10-20 18:27
edash-packager. The zlib.gyp dependency issue you encountered should be easy to solve, but there are some other tweaks needed to make it compile on Windows.

**Comment by gauravmishra** [comment] 2016-01-19 22:22
I get the same error on OS X (El Capitan). Is there a fix for this?

**Comment by kqyang** [comment] 2016-01-19 22:32
Mac OS is not supported yet. We are planning to support it soon! You may want to subscribe to  #21 to receive updates to this issue. In the mean time, you could try using [docker](https://github.com/google/edash-packager#Using%20docker%20for%20testing%20/development), with which you could run edash-packager on Mac.

**Comment by gggin** [comment] 2016-07-14 03:40
windows 10:
'python generate_version_string.py' returned exit status 1.
