### ISSUE TITLE
ninja: error: '../../packager/third_party/icu/source/common/bmpset.cpp'

### ISSUE THREAD

**Issue by rohitpal99** [google/edash-packager#19] opened 2015-06-20 09:51 UTC
Hi,
Trying to build on windows using ninja
ninja -C out/Debug
ninja: error: '../../packager/third_party/icu/source/common/bmpset.cpp', needed
by 'obj/third_party/icu/source/common/icuuc.bmpset.obj', missing and no known rule to make it

I guess repo don't have this 'icu' folder? How can I resolve this?

**Comment by tinskip** [comment] 2015-06-22 15:52
It sounds like you might have an invalid dependency pull.  Can you go to
the top level directory (where .gclient lives) and do a "gclient sync"?


On Sat, Jun 20, 2015 at 2:51 AM, RohitPal <notifications@github.com> wrote:

> Hi,
> Trying to build on windows using ninja
> ninja -C out/Debug
> ninja: error: '../../packager/third_party/icu/source/common/bmpset.cpp',
> needed
> by 'obj/third_party/icu/source/common/icuuc.bmpset.obj', missing and no
> known rule to make it
>
> I guess repo don't have this folder? How can I resolve this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/edash-packager/issues/19>.
>



-- 
Thomás Inskip | Software Engineer | tinskip@google.com | +1 650 241 9697

**Comment by rohitpal99** [comment] 2015-06-23 17:18
Hi,
Thanks for reply.

https://github.com/google/edash-packager/tree/master/packager/third_party/
icu directory is not present in git repo itself or I am missing something (icu/source/common/bmpset.cpp)

I did gclient sync as well but got no where.

**Comment by kqyang** [comment] 2015-06-23 17:27
Are you running in Windows? There are still some known problems with Windows build. Unfortunately we don't have bandwidth to work on Windows build yet. We will come back to it some time later.

**Comment by kqyang** [comment] 2015-07-14 00:48
Duplicate of issue #22

**Closed by kqyang** 2015-07-14 00:48 UTC
