### ISSUE TITLE
Can't sync on Mac OS X Yosemite

### ISSUE THREAD

**Issue by frapontillo** [google/edash-packager#10] opened 2015-03-16 17:54 UTC
When doing `gclient sync` the last command returns the following error:

```bash
MacBook:edash_packager fra$ gclient sync
Syncing projects: 100% (22/22), done.                              

________ running '/usr/bin/python src/packager/tools/clang/scripts/update.py --mac-only' in '/Users/fra/Workspace/edash_packager'
Clang already at 198389-1

________ running '/usr/bin/python src/gyp_packager.py --depth=src/packager' in '/Users/fra/Workspace/edash_packager'
Updating projects from gyp files...
gyp: /Users/fra/Workspace/edash_packager/src/packager/third_party/mach_override/mach_override.gyp not found (cwd: /Users/fra/Workspace/edash_packager)
Error: Command /usr/bin/python src/gyp_packager.py --depth=src/packager returned non-zero exit status 1 in /Users/fra/Workspace/edash_packager
```

What could be the cause? XCode is installed, and so are git and svn.

**Comment by kqyang** [comment] 2015-03-16 18:22
Unfortunately edash_packager is not supported yet in Mac OS X. We don't have resource to work on it right now, but we will probably look into it next quarter.

**Comment by orcaman** [comment] 2015-04-16 21:29
@kqyang what is the recommended OS for building then? Ubuntu? thanks.

**Comment by kqyang** [comment] 2015-04-21 19:31
Yes, it should work on most Linux systems, like Ubuntu, CentOS etc.

**Comment by kqyang** [comment] 2015-07-14 00:47
Duplicate of issue #21

**Closed by kqyang** 2015-07-14 00:47 UTC
